[package]
name = "pipe-gpt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.6" # For command-line argument parsing
openai_api_rust = "0.1.8" # For OpenAI API
reqwest = "0.11" # For making HTTP requests
tokio = { version = "1.0", features = ["full"] } # For asynchronous runtime